# Solutions to exercises
 
## Chapter 1

### 1.1

a. The sample space for this experiment consists of all the possible outcomes that could occur when you draw one jelly bean from the jar. In this case, the sample space consists of the following tree possible outcomes:

    S = {strawberry, blueberry, cinnamom}

    with straberry having probability 0.5, blueberry having probability 0.25, and cinnamon having probability 0.25.

b. The probability of event $A$ is the number of outcomes that satisfy the event divided by the total number of possible outcomes.

    In this case, there are two strawberry-flavored jelly beans in the jar and four total possible outcomes, so the probability of event $A$ is $\frac{2}{4} = \frac{1}{2}$  or 0.50.

    For the probability of event $B$ we have that there are three jelly beans that are not cinnamon-flavored in the jar and four total possible outcomes, so the probability of event $B$ is $\frac{3}{4}$ or 0.75.

c. Events $A$ and $B$ are not mutually exclusive because there is one outcome (strawberry) that satisfies both events. Specifically, event $A$ is satisfied by the two strawberry-flavored jelly beans in the jar, and event $B$ is satisfied by the two strawberry-flavored jelly beans and the one blueberry-flavored jelly bean.


### 1.2

def P(S, A, prob_dist):
    if set(A).issubset(set(S)):
        return sum([prob_dist[event] for event in A])
    else:
        return 0


S = {"strawberry", "blueberry", "cinammon"}
A = {"strawberry"}
prob_dist = {"straberry": 0.5, "blueberry": 0.25, "cinammon": 0.25}
P(S, A, prob_dist)